### ISSUE TITLE
[be.DB] - Reviews model

### ISSUE THREAD

**Issue by krab7191** [tlburchh/FourMusketeers#26]
This contains all wine reviews. Fields for: 

wineID (to know which one it was for), 

numericalRating (0-5), 

keyRating: array (stores unique IDs which associate with the keywords model (goodSpicy, badSour, etc)),

userID (the id of the user who created the review. If none exists, it was a guest review)

**Comment by HelpfulOwl** [comment]
Changed keyRatings field to keyWordRating.
